// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "DocPlaygroundsApp",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "DocPlaygroundsApp",
            targets: ["AppModule"],
            bundleIdentifier: "codes.rambo.samplecode.DocPlaygroundsApp",
            teamIdentifier: "8C7439RJLG",
            displayVersion: "1.0",
            bundleVersion: "2",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
			additionalInfoPlistContentFilePath: "MoreInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["./MoreInfo.plist"]
        )
    ]
)
